volumes:
  pgVector:
    name: "pgdata"
# Run this command to start the database:
# docker compose up
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    container_name: work_buddy_db
    ports:
      - 5431:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - pgVector:/var/lib/postgresql/data # Mounts the pgVector volume to the PostgreSQL data directory
